org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=/Applications/Android Studio.app/Contents/jbr/Contents/Home
android.useAndroidX=true
android.builder.sdkDownload=false
android.enableR8.fullMode=true
kotlin.code.style=official
